---
title: "GEOG 210B"
subtitle: "Class notes"
author: "Juan Carlos Villaseñor-Derbez"
output: html_document
---

# Labs

- [Lab 1](./Labs/Lab1/Lab1.html) - Intro to R and R Studio
- [Lab 2](./Labs/Lab2/Lab2.html) - Intro to linear regression

# Assignments

- [Assignment 1](./Assignments/Assig1/Assig1.pdf) - Intro to linear regression
    - [code](./Assignments/Assig1/Assig1.Rmd)
    
- [Assignment 2](./Assignments/Assig2/Assig2.pdf) - Matrix Linear Regression with R and Diagnostics
    - [code](./Assignments/Assig2/Assig2.Rmd)

- [Assignment 3](./Assignments/Assig3/Assig3.pdf) - Matrix Linear Regression with R and Diagnostics
    - [code](./Assignments/Assig3/Assig3.Rmd)

- [Assignment 4](./Assignments/Assig4/Assig4.pdf) - Matrix Linear Regression with R and Diagnostics
    - [code](./Assignments/Assig4/Assig4.Rmd)

# Lectures

- [Lecture 1](Lecture1.pdf) - Introduction
- [Lecture 2](Lecture2.pdf) - Random variables and PDFs
- [Lecture 3](Lecture3 - Linear regression intro.pdf) - Intro to linear regression
- [Lecture 4](Lecture4 - Matrix.pdf) - Matrix notation and regression decomposition
- [Lecture 5 & 6](Lecture5 - DiagnosticsGLS.pdf) - DiagnosticsGLS
- [Lecture 7](Lecture7 - Discrete Data  Maximum Likelihood.pdf) - Discrete Data  Maximum Likelihood
- [Lecture 8](Lecture8 - SpatialAnaylsis.pdf) - Spatial Analysis Part 1
    - [External resources](http://www.lpc.uottawa.ca/publications/moransi/moran.htm)
    
- [Lecture 9](Lecture9 - SpatialRegressionClassNotesFeb20.pdf) -Spatial regression
- [Lecture 10](Lecture10 - CountData.pdf) - Count data
- [Lecture 11](Lecture11 - SpatialPointsAnalysistoPost.pdf) - Spatial Point Analysis
- [Lecture 12](Lecture12.1 - IsaacsSrivastavaOrdKrigtoPost.pdf) - Kriging
- [Lecture 13](Lecture12.2 - GeostatisticsPart2topost.pdf) -  Geostats
- [Lecture 13]() - 
- [Lecture 14]() - 
- [Lecture 15]() - 

# Labs

- [Lab 1](Labs/Lab1/Lab1.html)
- [Lab 2](Labs/Lab2/Lab2.html)
- [Lab 3](Labs/Lab3/Lab3.html)
